// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../../packages/FSharp.Formatting/lib/net40/CSharpFormat.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/FSharp.CodeFormat.dll"
#r "../../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/FSharp.Formatting.Common.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/FSharp.Literate.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/FSharp.Markdown.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/FSharp.MetadataFormat.dll"
#r "../../../packages/FSharpVSPowerTools.Core/lib/net45/FSharpVSPowerTools.Core.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/RazorEngine.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Drawing.dll"
#r "System.Numerics.dll"
#r "../../../packages/FSharp.Formatting/lib/net40/System.Web.Razor.dll"
#r "System.Xml.dll"
#r "System.Xml.Linq.dll"