// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "System.Core.dll"
#r "System.dll"
#r "System.Drawing.dll"
#r "System.Numerics.dll"
#r "System.Xml.dll"
#r "System.Xml.Linq.dll"
#r "../bin/Debug/CSharpFormat.dll"
#r "../bin/Debug/FSharp.CodeFormat.dll"
#r "../bin/Debug/FSharp.Compiler.Service.dll"
#r "../bin/Debug/FSharp.Formatting.Common.dll"
#r "../bin/Debug/FSharp.Literate.dll"
#r "../bin/Debug/FSharp.Markdown.dll"
#r "../bin/Debug/FSharp.MetadataFormat.dll"
#r "../bin/Debug/FSharpVSPowerTools.Core.dll"
#r "../bin/Debug/RazorEngine.dll"
#r "../bin/Debug/System.Web.Razor.dll"