name: Deploy to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: False

      - name: Get paket
        shell: bash
        run:
          dotnet tool restore

      - name: Generate website content
        shell: bash
        run: mkdir ../output/ && echo 'regenerate' | dotnet fsi tools/update.fsx

      - name: Publish to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'luweiblog'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '../output'